return {
    {path='sheerun/vim-polyglot', plugModule='polyglot'},
    {path="nvim-lualine/lualine.nvim", plugModule='lualine-setup'},
    {path='nvim-lua/plenary.nvim'},
    {path='nvim-telescope/telescope.nvim'},
    {path="neovim/nvim-lspconfig"},
    {path="hrsh7th/nvim-cmp"},
    {path="hrsh7th/cmp-nvim-lsp"},
    {path="saadparwaiz1/cmp_luasnip"},
    {path="L3MON4D3/LuaSnip"},
    {path="mhinz/vim-signify"},
    {path="kshenoy/vim-signature"},
    {path="glepnir/dashboard-nvim", plugModule='dashboard_config'},
    {path="folke/persistence.nvim"},
    {path="dylanaraps/wal.vim"},
    {path="kyazdani42/nvim-web-devicons"}, -- for file icons
    {path="kyazdani42/nvim-tree.lua", plugModule='nvim-tree-setup'},
    {path="nvim-treesitter/nvim-treesitter"},
    {path="morhetz/gruvbox"},
    {path="folke/tokyonight.nvim", branch = "main"},
    {path="Mofiqul/vscode.nvim"},
    {path="akinsho/toggleterm.nvim", plugModule='toggleterm-setup'},
    --{path="lukas-reineke/indent-blankline.nvim", plugModule='indent-blankline-setup'},
    {path="akinsho/bufferline.nvim", plugModule='bufferline-setup'},
    {path="overcache/NeoSolarized"},
    {path="cocopon/iceberg.vim"},
    {path="BurntSushi/ripgrep"},
    {path="sharkdp/fd"},
    {path="vimwiki/vimwiki"}
}
